parameters:


services:
  _defaults:
    autowire: true
    autoconfigure: true

  Norvutec\CronManagerBundle\Controller\CronManagementController: ~
  Norvutec\CronManagerBundle\Command\:
    resource: '../src/Command'
    autowire: true
    tags: [ console.command ]
  Norvutec\CronManagerBundle\Repository\:
    resource: '../src/Repository'
    tags: [ doctrine.repository_service]
  Norvutec\CronManagerBundle\Service\CronManagerService:
    autowire: true
    autoconfigure: true
    public: true
    tags: [ norvutec.cron_manager_bundle.service ]