services:
  _defaults:
    autowire: true
    autoconfigure: true

  Norvutec\CronManagerBundle\Controller\CronManagementController: ~
  Norvutec\CronManagerBundle\Command\:
    resource: '../src/Command'
  Norvutec\CronManagerBundle\Command\CronManagerRunCommand:
    bind:
      $projectDir: '%kernel.project_dir%'
  Norvutec\CronManagerBundle\Repository\:
    resource: '../src/Repository'
    tags: [ doctrine.repository_service]
