parameters:


services:
  _defaults:
    autowire: true
    autoconfigure: true

  Norvutec\CronManagerBundle\Controller\CronManagementController: ~
  Norvutec\CronManagerBundle\Service\CronManagerService: ~
  Norvutec\CronManagerBundle\Command\:
    resource: '../src/Command'
    autowire: true
    tags: [ console.command ]